model_params:
  model: smp.Unet
  encoder_name: &encoder_name efficientnet-b0
  classes: 4
  activation: null

args:
  logdir: "./logs/clouds_logs"
  seed: 65
  check: False
  verbose: True

distributed_params:
  opt_level: O1

stages:
  data_params:
    batch_size: 8
    num_workers: 4
    path: ../../input/dataset_320x640
    image_folder: train_images
    df_train_name: "train.csv"
    model_name: *encoder_name
    type: test

  infer_final:
    state_params:
      num_epochs: 1

    data_params:
      type: test
      batch_size: 8

    callbacks_params:
      loader:
        callback: CheckpointCallback
        resume:  logs/clouds_logs/checkpoints/best.pth

      inference:
        callback: CustomInferCallback
        threshold: 0.4
        min_size: 15000
        path: "../../input/dataset_320x640"
